### ISSUE TITLE
Project filtering is **really** slow

### ISSUE THREAD

**Issue by alexis-** [Serg046/MsBuildTaskExplorer#36]
When I search for a project with the new filtering feature, my CPU usage climbs to the roof, and filtering is very slow (several seconds).

**Comment by Serg046** [comment]
That's why `Refresh` button was initially added. I am not sure if I will be able to improve the performance (maybe we can parallel it) itself but I plan to add a delay between received symbols, so that it will let you a way to type the whole search expression first.

But this one should be implemented first Serg046/EventBinder#12

**Comment by Serg046** [comment]
- The performance has been improved
- The event has been debounced (500ms)

**Comment by alexis-** [comment]
I have been using it for the past few days without issue. Your improvement made filtering and MSBuildTaskExplorer as a whole much more usable. Great job
